version: '3.6'

services:
  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: "${REACT_APP_API_URL}"
    ports:
      - "4000:3000"
  api-gateway:
    build: ./api-gateway    
    environment:
      NVISION_API_KEY: "${NVISION_API_KEY}"
      NVISION_API_URL: "https://nvision.nipa.cloud/api/v1"
    ports:
      - "5005:5000"
    
  